const errors = {
  A0: 'The value does not match the expected type. Please refer to the API documentation.',
  A1: 'Email is registered.',
  A2: 'Email unrecognized.',
  A3: 'First name is required.',
  A4: 'Last name is required.',
  A5: 'OTP has expired.',
  A6: 'Max attempts reached, please request a new OTP.',
  A7: 'OTP is incorrect.',
  A8: 'Successfully logged in.',
  A9: 'The requested entity with the provided id does not exists.',
  A10: 'Invalid id.',
  A11: 'Email is required.',
  A12: 'Entity does not exists.',
  A13: 'Id is required.',
  A14: 'You do not appear to be the author of this post.',
  A15: 'Can not create empty posts.',
  A16: 'Missing data.',
  A17: 'Already liked',
  A18: 'Can not dislike',
  A19: 'Already shared',
  A20: 'Can not unshare',
  A21: 'Can not like or share your own posts.',
  A22: 'Can not affect others comments',
  A23: 'The post does not have an event',
  A24: 'Can not join your own event.',
  A25: 'Already on pending list.',
  A26: 'You have been rejected from this event.',
  A27: 'You are not allowed to join this event',
  A28: 'No places left in the event',
  A29: 'You have already joined the event',
  A30: 'You can not leave this event.',
  A31: 'User is not in rejected list.',
  A32: 'Event start date has passed.',
  A33: 'User is not a rejected participant.',
  A34: 'User is not pending approval.',
  A35: 'Pending request already exists.',
  A36: 'Offset is required',
  A37: 'Limit is required',
  A38: 'There is not pending request from this user.',
  A39: 'You are not friends with this user.',
  A40: 'You are not the admin of this group.',
  A41: 'You are already member of this group.',
  A42: 'You are not a member of this group. ',
  A43: 'You are the admin of the group and can not leave it.',
  A44: 'You are not allowed to view or manipulate this notification.',
	A45: 'Allowed between 2 and 100 participants',
};

export default errors;
